### ISSUE TITLE
Cannot find module socket.io-node

### ISSUE THREAD

**Issue by markc** [robrighter/node-boilerplate#1] opened 2010-08-18 14:30 UTC
Excellent package, however, I followed the instructions after a clone but got this error...

```
~/node/node-boilerplate node project/app.js
node.js:289
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'socket.io-node'
 at loadModule (node.js:289:15)
 at require (node.js:420:14)
 at Object.<anonymous> (/home/markc/node/node-boilerplate/project/app.js:6:12)
 at Module._compile (node.js:472:25)
 at Module._loadScriptSync (node.js:482:10)
 at Module.loadSync (node.js:352:12)
 at Object.runMain (node.js:535:24)
 at node.js:760:10
```

**Comment by trvsdnn** [comment] 2010-08-18 20:20
I had a similar issue. I was able to fix it by updating node to the latest version... maybe check that if you haven't already?

**Comment by robrighter** [comment] 2010-08-18 21:45
I tried reproducing this on a few machines. But could not get the error to occur.

**Comment by techwraith** [comment] 2010-08-18 21:56
You can fix this error by changing:

```
, io = require('socket.io-node')
```

to

```
, io = require('Socket.IO-node')
```

It seems like capitalization is key here.

**Comment by robrighter** [comment] 2010-08-18 22:12
Thanks Techwraith, just pushed a fix patch.

**Comment by techwraith** [comment] 2010-08-18 22:36
No problem, thanks for pushing the patch. Love what you've done here!

**Comment by robdrimmie** [comment] 2010-08-19 01:02
I encountered a similar error with node v0.1.98-31-g1c6671a. Upgrading to 0.1.104 resolved the problem.

**Closed as completed** 2010-08-19 04:43 UTC

**Comment by cawoodm** [comment] 2011-09-06 13:09
It looks to me like this issue is still open on the latest versions (5.4 & 5.5) under windows. For example, I get this error when I try to run node-inspector. Maybe it's because I have to install the module socket.io but I can't seem to find out how...
